# Generated by Django 4.0.5 on 2022-06-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=225)),
                ('telephone', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=225)),
                ('fax', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=225)),
                ('is_status', models.BooleanField(default=True)),
                ('currency_symbol', models.CharField(max_length=225)),
                ('currency_formal_name', models.CharField(max_length=225)),
                ('financial_year', models.DateField()),
                ('books_beginning_from', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=225)),
                ('registration_type', models.CharField(max_length=225)),
                ('gst_applicable_from', models.DateField()),
                ('gst_uin', models.CharField(max_length=225)),
                ('periodicity_of_gst', models.CharField(max_length=225)),
                ('alter_gst_rate_dtls', models.BooleanField(default=False)),
                ('tax_liabilty_on_advanced_recipts', models.BooleanField(default=False)),
                ('tax_liabilty_on_reverse_charge', models.BooleanField(default=False)),
                ('gst_classification', models.BooleanField(default=False)),
                ('lut_bond_dtls', models.BooleanField(default=False)),
                ('bill_applicable', models.BooleanField(default=True)),
                ('applicable_from', models.DateField()),
                ('threshold_limt_includes', models.CharField(max_length=225)),
                ('threshold', models.CharField(default='50,000', max_length=225)),
                ('applicable_for_intrastate', models.BooleanField(default=True)),
                ('threshold_limit', models.CharField(default='50,000', max_length=225)),
                ('print_e_bill_with_invoice', models.BooleanField(default=False)),
                ('e_invoicing_applicable', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_accounts', models.BooleanField(default=True)),
                ('enable_bill_wise_entry', models.BooleanField(default=True)),
                ('maintain_inventory', models.BooleanField(default=True)),
                ('integrate_accounts_with_inventory', models.BooleanField(default=True)),
                ('enable_gst', models.BooleanField(default=True)),
                ('enable_tds', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companymodel')),
            ],
        ),
    ]
