# Generated by Django 4.0.5 on 2022-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='currency_formal_name',
            field=models.CharField(default='INR', max_length=225),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=225),
        ),
    ]
