# Generated by Django 4.0.5 on 2022-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_companymodel_currency_formal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
