# Generated by Django 4.0.5 on 2022-06-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_companymodel_is_valid_companymodel_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_Features',
        ),
    ]
