# Generated by Django 4.0.5 on 2022-06-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_company_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_accounts', models.BooleanField(default=True)),
                ('enable_bill_wise_entry', models.BooleanField(default=True)),
                ('maintain_inventory', models.BooleanField(default=True)),
                ('integrate_accounts_with_inventory', models.BooleanField(default=True)),
                ('enable_gst', models.BooleanField(default=True)),
                ('enable_tds', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companymodel')),
            ],
        ),
    ]
