# Generated by Django 4.0.5 on 2022-06-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_company_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_Features',
            new_name='Company_Feature',
        ),
    ]
