# Generated by Django 4.0.5 on 2022-06-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_company_features_company_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_feature',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companymodel'),
        ),
    ]
