# Generated by Django 4.0.5 on 2022-06-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_company_feature_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gst',
            name='threshold',
        ),
    ]
