# Generated by Django 4.0.5 on 2022-06-10 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_gst_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companymodel'),
        ),
    ]
