# Generated by Django 4.0.5 on 2022-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_selected_companies_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('gp_behaves_like_sub_ledger', models.BooleanField(default=False)),
                ('nett_debit_credit_bal_reporting', models.BooleanField(default=False)),
                ('used_for_calculation', models.BooleanField(default=False)),
                ('method_to_allocate_usd_purchase', models.BooleanField(default=False)),
            ],
        ),
    ]
