# Generated by Django 4.0.5 on 2022-06-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_groupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='method_to_allocate_usd_purchase',
            field=models.CharField(max_length=225),
        ),
    ]
