# Generated by Django 4.0.5 on 2022-06-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_groupmodel_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='under',
            field=models.CharField(max_length=225),
        ),
    ]
