# Generated by Django 4.0.5 on 2022-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_groupmodel_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='alias',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
