# Generated by Django 4.0.5 on 2022-06-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_ledgermodel_taxregistermodel_mailingaddressmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingaddressmodel',
            name='provide_banking_details',
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='provide_banking_details',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
