# Generated by Django 4.0.5 on 2022-06-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_mailingaddressmodel_provide_banking_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgermodel',
            old_name='group_id',
            new_name='group',
        ),
    ]
