# Generated by Django 4.0.5 on 2022-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_vouchermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=225)),
                ('fname', models.CharField(max_length=225)),
                ('iso_code', models.CharField(max_length=225)),
                ('n_deci_placs', models.CharField(max_length=225)),
                ('smt_millon', models.BooleanField()),
                ('symbol_to_amount', models.BooleanField()),
                ('space_bt_sy', models.BooleanField()),
                ('amount_after_decimal', models.CharField(max_length=225)),
                ('amount_in_words', models.CharField(max_length=225)),
            ],
        ),
    ]
