# Generated by Django 4.0.5 on 2022-06-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_currencymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('item_be_added', models.BooleanField()),
                ('alter', models.BooleanField()),
            ],
        ),
    ]
