# Generated by Django 4.0.5 on 2022-06-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_stockcategorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=225)),
                ('salias', models.CharField(max_length=225)),
                ('sunder', models.CharField(max_length=225)),
                ('units', models.CharField(max_length=225)),
                ('gst_applicable', models.CharField(max_length=225)),
                ('alter_gst_details', models.BooleanField()),
                ('typ_supply', models.CharField(max_length=225)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companymodel')),
            ],
        ),
    ]
