# Generated by Django 4.0.5 on 2022-06-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_stockitemcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemcreation',
            name='rate_duty',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
