# Generated by Django 4.0.5 on 2022-06-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_stockitemcreation_rate_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemcreation',
            name='sunder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockgroupmodel'),
        ),
    ]
